### ISSUE TITLE
No existing eHSN files can be loaded

### ISSUE THREAD

**Issue by TheRealDougSchmidt** [ECCC-MSC/WSC-EHSN#2]
v1.3.1 of the eHSN GUI is unable to load any files from v1.3 or earlier, since they all are missing the `<surveyedBy>` element in the `<LevelChecks>` node.

The GUI is failing silently, and behaving as if the following XML content is empty.

**Comment by AnojanS** [comment]
Hi, I'm Anojan the student currently working with eHSN. The error occurs because the "surveyed by" section was recently added to eHSN so eHSN will throw an error when it searches for it from past XML files. Despite the error, any XML file should still open fine. I've updated the repository so that the error is surpressed, however if the error is preventing you from opening older XML files at all could you please attach the files causing you trouble.

Thanks,
Anojan

**Comment by DougStiff** [comment]
Hi Other Doug.
Can you attach one of your failing XML files? We tested old field visits and it seems to load them and see the data.... 
Other Doug.

**Comment by TheRealDougSchmidt** [comment]
Here's one of the XML files (extension was renamed from .XML to .TXT so that GitHub would upload it)

[05BG006_20180801_v1.xml.txt](https://github.com/ECCC-MSC/WSC-EHSN/files/2895318/05BG006_20180801_v1.xml.txt)

Here's the PDF generated from v1.3_Beta:
[05BG006_20180731_FV_VIEW.v1.3_Beta.pdf](https://github.com/ECCC-MSC/WSC-EHSN/files/2895308/05BG006_20180731_FV_VIEW.v1.3_Beta.pdf)

And the PDF generated from v1.3:
[05BG006_20180731_FV_VIEW.v1.3.1.pdf](https://github.com/ECCC-MSC/WSC-EHSN/files/2895309/05BG006_20180731_FV_VIEW.v1.3.1.pdf)

The Moving Boat tab was correctly displayed in v1.3_Beta:
![05bg006_20180801_v1 movingboat v1 3_beta](https://user-images.githubusercontent.com/54773/53264569-c6cc9e80-3690-11e9-8d56-987949266aed.png)

But the tab was completely empty in v1.3.1:
![05bg006_20180801_v1 movingboat v1 3 1](https://user-images.githubusercontent.com/54773/53264568-c6cc9e80-3690-11e9-8859-c02fe2a4cb29.png)

Without the added try/finally guard block, an XML file from any version earlier than v1.3.1 would stop parsing the XML in the middle of the level check node, and all following information (essentially anything not shown on the front page, would be blank and would be lost when saved).

**Comment by TheRealDougSchmidt** [comment]
Perhaps there is a difference in raised exceptions when the app is built via pyInstaller. (which I think is how the app is deployed by WSC).

I'm just building it from source, and debugging it using PyCharm. Perhaps that environment stops-on-first-exception, and pyInstaller doesn't?

**Comment by DougStiff** [comment]
Pushed and tested, thanks Doug.  Closing this issue.
